name: trigger-draw
on:
  push:
  pull_request:
    branches: [ master ]
permissions:
  contents: write

jobs:
  hash_names:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout private repo
        uses: actions/checkout@v3
      - name: Create name-hash combos
        run: ./scripts/hasher.sh ./lists
      - name: Commit to private repo
        run: |
          git add .
          git config --global user.name "hashbot"
          git commit -m "updated hashes" 
          git push
      - uses: actions/checkout@v3
        name: Checkout public repo
        with: 
          repository: "cluelessuk/cool-test-public"
          path: ./public
      - name: Create hashes for public repo
        run: ./scripts/hash-only.sh ./lists ./public
      - name: Commit to public repo
        run: |
          git add .
          git config --global user.name "hashbot"
          git commit -m "updated hashes" 
          git push

